# Config file for Phylomera v8
# Make sure each line can be read as a bash command
# SCRIPTS is the folder that contains phylomera internal scripts such as make_partition_from_probe2.py, drop_short_seq.py, clean_amas_partition.py

MAFFT="mafft"
HMMCLEANER="HmmCleaner.pl"
OMM_MACSE="/opt/omm_macse/OMM_MACSE/S_OMM_MACSE_V12.02.sh"
IQTREE3="iqtree3"
PARALLEL="parallel"
AMAS="$(find /opt/miniconda3/lib/ -name "python3.*/site-packages/amas/AMAS.py")"
SEQKIT="seqkit"
SCRIPTS="/opt/gabbi/scripts"
